title: B'more on Rails Workshop Tutorial
email: bmoreonrailsworkshop.gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The official tutorial for the B'more on Rails Workshop!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: BmorRailsSchool
github_username: bmoreonrails

collections:
  chapters:
    output: true

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
